---
title: "9.2 Allocation Models (nonlinear approach)"
author: "Mark Newman"
output:
  html_document: default
editor_options: 
  chunk_output_type: console
---

The intent of this extended example is to look at how to solve a clasic lp formulation using a nonlinear solver to see how the different R packages work. 

# LP Formulation

Descision variables

$X = x_{c}, x_{d}, x_{t}$

* (c)hair, (d)esk, (t)able

Objective function

* Maximize: $15x_{c} + 24x_{d} + 18x_{t}$
  
Subject to

* Fabrication: $4x_{c} + 6x_{d} + 2x_{t} <= 1850$
* Assembly: $3x_{c} + 5x_{d} + 7x_{t} <= 2400$
* Shipping: $3x_{c} + 2x_{d} + 4x_{t} <= 1500$
* Demand Potential:
    * $x_{c} <= 360$
    * $x_{d} <= 300$
    * $x_{t} <= 100$

# R translation

**Process**

* Clear everything
* Required packages
* Add objective function
    * `nloptr` only solves for the minimum. So to maxmize $f(x)$ we just minimize $-f(x)$
* Add in all constraints
    * `nloptr` only allows a function to evaluate the parameters. `eval_g_ineq(...)` is used when the equation can be re-writen as $xxx <= 0$ and `eval_g_eq` is for when it can be re-writen as $xxx = 0$.
        * In this example we only have the form $xxx <= 0$ so we only need `eval_g_ineq(...)`.
* Solve
    * When using a non-linear solver, always do at least 2 starting positions. Upper (`ub`) and lower (`lb`) bounds are usualy good bets.
    * Use `-1*model1$objective` because we fliped the objective when converting max to min.
    * `-1*model1$objective` == `-1*model2$objective`
        * $Objective = 8400$
    * `model1$solution` == `model2$solution`
        * $X = 0,275,100$

**R Results**

Make profit of $8,400 by building the below

* 0 chairs
* 275 desks
* 100 tables

**Book results**

Per page 245 "As shown in Figure 9.6, ... no chairs, 275 desks, and 100 tables... maximum profit contributation is $8,400..."

**Code**
```{r results="hold"}
rm(list = ls())
options(scipen = 999)
if (!require('nloptr')) install.packages('nloptr', quiet=TRUE)
library(nloptr)
eval_f = function(x) {
  
    objective = -1*(15*x[1] + 24*x[2] + 18*x[3])

    return (objective)
}
eval_g_ineq = function(x) {
  
  objective = c(
    4*x[1] + 6*x[2] + 2*x[3] - 1850,
    3*x[1] + 5*x[2] + 7*x[3] - 2400,
    3*x[1] + 2*x[2] + 4*x[3] - 1500
  )

  return (objective)
}
lb = c(0,0,0)
ub = c(360,300,100)
sp1 = lb
sp2 = ub
opts = list(algorithm="NLOPT_LN_COBYLA", maxeval=4000)
model1 = nloptr(x0 = sp1, eval_f = eval_f, eval_g_ineq = eval_g_ineq, lb = lb, ub = ub, opts = opts)
model2 = nloptr(x0 = sp2, eval_f = eval_f, eval_g_ineq = eval_g_ineq, lb = lb, ub = ub, opts = opts)
-1*model1$objective
-1*model2$objective
round(model1$solution, 2)
round(model2$solution, 2)
print(model1)
print(model2)
```

