#' From + To 2 DV
#'
#' \code{fromTo2DV} creates a list Descision variables
#'
#' @param from a vector of names of the "From" variables
#' @param to a vector of names of the To" variables
fromTo2DV = function(from, to) {
  
  l1 = length(from)
  l2 = length(to)
  vars = vector(mode = "character", length = (l1*l2))
  
  p = 1
  for(i in 1:l1) {
    for(j in 1:l2) {
      vars[p] = sprintf("%s%s", from[i], to[j])
      p = p + 1
    }
  }

  return(vars)
}

#' Capacity Requirments
#' 
#' \code{CapacityRequirments} generates a all the capacity requirments
#' variables, assuming the DVs are in the order generated by
#' \link{\code{fromTo2DV}}
CapacityRequirments = function(from, to) {
  
  res = matrix(0, nrow=from, ncol = (from*to))
  
  for(i in 1:from) {
    for(j in 1:to) {
      res[i,(i-1)*to+j] = 1
    }
  }
  
  if(!all(rowSums(res) == to)) { warning("Double check failed") }
  
  return(res)
}

DemandRequirments = function(from, to) {
  
  res = matrix(0, nrow=to, ncol = (from*to))
  
  for(i in 1:to) {
    v = rep_len(0,to)
    v[i] = 1
    res[i,] = rep_len(v, from*to)
  }
  
  if(!all(rowSums(res) == from)) { warning("Double check failed") }
  
  return(res)
}

IdMat = function(dim) {
  
  res = matrix(0, nrow=dim, ncol = dim)
  
  for(i in 1:dim) {
    res[i,i] = 1
  }

  return(res)
}

LinkRequirments = function(direction, from, to, M) {
  
  res = if(direction == "from") { CapacityRequirments(from, to) } else { DemandRequirments(from,to) }
  d = dim(res)
  pad = IdMat(d[1])*-M
  
  res = cbind(pad, res)
  
  return(res)
}
